### ISSUE TITLE
constexpr build failure on clang

### ISSUE THREAD

**Issue by rokups** [yse/easy_profiler#108]
```
In file included from /home/travis/build/rokups/Urho3D/Source/ThirdParty/easy_profiler/easy_profiler_core/include/easy/details/arbitrary_value_public_types.h:46:
/home/travis/build/rokups/Urho3D/Source/ThirdParty/easy_profiler/easy_profiler_core/include/easy/details/arbitrary_value_aux.h:70:44: error: 
      constexpr constructor never produces a constant expression
      [-Winvalid-constexpr]
        explicit inline EASY_CONSTEXPR_FCN ValueId(const void* _member) ...
                                           ^
/home/travis/build/rokups/Urho3D/Source/ThirdParty/easy_profiler/easy_profiler_core/include/easy/details/arbitrary_value_aux.h:70:80: note: 
      reinterpret_cast is not allowed in a constant expression
  ...inline EASY_CONSTEXPR_FCN ValueId(const void* _member) : m_id(reinterpre...
```

For time being i removed `EASY_CONSTEXPR_FCN`. Not sure if this is a proper fix or what proper fix would be.

**Comment by rationalcoder** [comment]
That's probably the right thing to do. Clang is right according to the standard. reinterpret_cast and any casting business with void* 's isn't allowed in constexpr anything.

**Comment by cas4ey** [comment]
Hi @rokups !
Yeah, my bad :-)

Can you try to replace `vin_t` in `ValueId` with `const void*` for `ValueId::m_id` and cast it to number only during serialization [here](https://github.com/yse/easy_profiler/blob/develop/easy_profiler_core/thread_storage.cpp#L65) (replace `_vin.m_id` with 'reinterpret_cast<vin_t>(_vin.m_id)') ?

**Comment by rokups** [comment]
@cas4ey clang approves change you suggested :)

**Comment by cas4ey** [comment]
Closing for now. Let me know if any problems occur.
