### ISSUE TITLE
Looking forward to QtCreator integration

### ISSUE THREAD

**Issue by ElderOrb** [yse/easy_profiler#11]
Keep up great work, guys!

**Comment by cas4ey** [comment]
Thanks!
But we need help here because we have no experience of creating plugins for QtCreator.

**Comment by cas4ey** [comment]
I think this issue should be closed as there are no interested people...
@ElderOrb am I right?

**Comment by rationalcoder** [comment]
@cas4ey Ohhhh. I just realized cas4ey => Victor that I have been emailing, haha. I had originally thought this this issue was for designing the GUI differently with .ui files. If you guys ever want to do anything like that, I have a lot of experience with Qt.

**Comment by rokups** [comment]
> I think this issue should be closed as there are no interested people...

There is little point in sticking profiler GUI into IDE. Profiler being able to profile application startup kind of negates need for IDE integration altogether.
