### ISSUE TITLE
Не запускается profiler_gui под Linux

### ISSUE THREAD

**Issue by WinPooh32** [yse/easy_profiler#12]
Вывод:
`./profiler_gui: error while loading shared libraries: libeasy_profiler.so: cannot open shared object file: No such file or directory`

вот что ldd показывает:
`	
        libeasy_profiler.so => not found
`
`
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f94f917e000)
`
`
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f94f8c36000)
`
`
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f94f8760000)
`
`
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f94f83dd000)
`
Библиотеки эти я вижу в папке с бинарником.
Возможно, использование в CMake команды `link_directories(directory1 directory2 ...)` решит проблему.

**Comment by yse** [comment]
Лучше всего использовать в таких случаях переменную окружения `LD_LIBRARY_PATH`, куда дописать путь до директории с so-файлом

**Comment by alexey-lysiuk** [comment]
Из чистого любопытсва: почему либа только динамическая и нет опции для выбора её типа?

**Comment by yse** [comment]
> почему либа только динамическая
В ядре есть класс-синглтон. Чтобы особых проблем не было (особенно на Windows), решили запихнуть всё в динамическую либину. Хотя под линуксом можно попробовать статическую либину. 

> нет опции для выбора её типа?
Дельное замечание, спасибо! Вынесем наружу некоторые настройки.
