### ISSUE TITLE
-std=gnu++11 c++ flags leaks into users's c and C++ compiler flags

### ISSUE THREAD

**Issue by mchiasson** [yse/easy_profiler#126]
It generates this warning on linux gcc when compiling a c file from a mixed C and C++ project:
```
cc1: warning: command line option ‘-std=gnu++11’ is valid for C++/ObjC++ but not for C
```

This public/leaking flag can also potentially interfere with C++14 and C++17 users

**Comment by yse** [comment]
I think it's relating to #71
