### ISSUE TITLE
arbitrary_value.h does not include profiler.h

### ISSUE THREAD

**Issue by mmallet-youilabs** [yse/easy_profiler#134]
This is a minor issue. When doing:
```
#include <easy/arbitrary_value.h>
#include <easy/profiler.h>
```
, a compilation error results as `easy/arbitrary_value.h` doesn't include `easy/profiler.h`. The fix would appear to be to include `profile.h` first, but if an app uses headers sorting then the 'normal' sorting results in a compilation error.

`arbitrary_value.h` should be updated to include `profile.h` (or, better yet, including `easy/details/profiler_public_types.h`)

**Comment by cas4ey** [comment]
Hi @mmallet-youilabs  
Thanks for reporting!  
Fixed :)

**Comment by mmallet-youilabs** [comment]
:awwyeah:
