### ISSUE TITLE
Cannot read profiled blocks error

### ISSUE THREAD

**Issue by nayefc** [yse/easy_profiler#135]
Hi 

I tried both dumping to a file and streaming over network from a linux machine to macOS. I get this error:
```
Cannot read profiled blocks
Reason: wrong memory size == 0 for 0 blocks
```

Any ideas why I'm seeing this? Seems like its a bad file format, and bad streaming packets getting transported as well?

**Comment by cas4ey** [comment]
Hi @nayefc  
Please remove top-level blocks which are not going to finish (or close them explicitly before dumping data). See last couple comments of #115 for more details  
For example:
```cpp
int main()
{
    EASY_PROFILER_ENABLE;
    EASY_BLOCK("main"); // This block is not going to finish until main() returns - remove it
    while (!finish)
    {
        EASY_BLOCK("Main frame");
        . . .
    }
    . . .
    profiler::dumpBlocksToFile("..."); // No data will be dumped because top-level block is still opened
}
```

**Comment by nayefc** [comment]
I dont have a main block as such. Here's what I have:

```
int main() {
    EASY_PROFILER_ENABLE;
    profiler::startListen();
    func()
    // profiler::dumpBlocksToFile("test_profile.prof"); <-- in case I am writing to file not over network
}
```

Then:

```
void func()
{
    EASY_FUNCTION(profiler::colors::Magenta);
    EASY_BLOCK("Parsing JSON");
    .... parse json
    EASY_END_BLOCK;
}
```

**Comment by nayefc** [comment]
I think EASY_FUNCTION also needs to be closed manually. Removing the loop thing works but when I reintroduce it it doesn't work. So basically just remoivng EASY_FUNCTION an dhaving EASY_BLOCK & end only still throws an error.

**Comment by nayefc** [comment]
I figured it out it, thanks!

**Comment by Levi-Armstrong** [comment]
> I figured it out it, thanks!

@nayefc how did you resolve your issue?
