### ISSUE TITLE
Only single main block shows in GUI

### ISSUE THREAD

**Issue by nayefc** [yse/easy_profiler#136]
Hi,

I am running this with multiple blocks to track functions but I'm only seeing my main block.
 
<img width="885" alt="screenshot 2018-10-28 at 08 51 55" src="https://user-images.githubusercontent.com/1350418/47616151-4190fe80-da8f-11e8-89d9-a5059bc53517.png">

The code with the other non-main blocks is running though (it 100% is running). Why is this happening? I have a function that gets called a lot in a loop that I just added an EASY_BLOCK at the top of it. So:

```
int main() {
    EASY_PROFILER_ENABLE;
    EASY_BLOCK("main");
    while (true) { // this is a more complicated loop that runs until ctrl-c is invoked which is handled
        func()
    }
    EASY_END_BLOCK;
    profiler::dumpBlocksToFile("test_profile.prof");
}
```

```
void func()
{
    EASY_BLOCK("Handling JSON", profiler::colors::Red);
    .... parse json
    EASY_END_BLOCK;
}
```

However, I'm seeing this red colour which may refer to this Red block I have but how can I see its info? The table shows main only and nothing else. Not even the name of the red block.

Any ideas?

**Comment by cas4ey** [comment]
Hi @nayefc  
Your example seems OK to me...  
Please, try to get familiar with `profiler_sample` project - maybe you will find some differences, - or give some more details.  
It would be nice to hear from you after you will find what is going wrong too.
