### ISSUE TITLE
Use profiler without gui

### ISSUE THREAD

**Issue by qavl** [yse/easy_profiler#158]
Is it possible to study profile results in terminal? You provide awesome GUI, but sometimes I need to simply run on an external server and identify the most heavy functions.

**Comment by yse** [comment]
Hello. Thanks for positive feedback! 
1. There is half alive command line tool - [easy_profiler_converter](https://github.com/yse/easy_profiler/tree/develop/easy_profiler_converter). The tool can generate json with information about blocks. But unfortunately it not tested enough =(
2. Are you tried to connect to external server via gui? Or simply store file, download it and view in the gui tool?
