### ISSUE TITLE
Cannot enter bookmark text on mac

### ISSUE THREAD

**Issue by nedm2** [yse/easy_profiler#165]
Thanks for your great work on easy_profiler and for the new release!

I just checked out v2.1.0 and built on mac to try out the new bookmark feature. I can add bookmarks but cannot set any text for them. A cursor appears in the text box but it will not accept any text (i.e. nothing happens when I type). 

I am building against Qt 5.9.2. 

I haven't tried on linux yet, will see when I get to the office tomorrow.

**Comment by nedm2** [comment]
A couple more data points: 

linux with Qt 5.9.8: works correctly
linux with Qt 5.12.5: works correctly

mac with Qt 5.12.5: GUI freezes when I attempt to add a bookmark

**Comment by yse** [comment]
Hello! Thank a lot for reporting!
Problem was with some custom headers for window.
