### ISSUE TITLE
Can't find the way to see EASY_VALUE and EASY_EVENT

### ISSUE THREAD

**Issue by andreyryabov** [yse/easy_profiler#182]
Apple clang version 11.0.0 (clang-1100.0.33.17)
Target: x86_64-apple-darwin19.4.0
Thread model: posix

```
#include <string>
#include <easy/profiler.h>
#include <easy/arbitrary_value.h>

void test() {
    EASY_FUNCTION();
    EASY_VALUE("v1", 111);
    EASY_EVENT("e1", 222);
}

int main() {
    EASY_PROFILER_ENABLE;

    test();

    profiler::dumpBlocksToFile("test_profile_values.prof");
}

```
Where do I see the actual values for 'v1' and 'e2' ?

![bdb873100bfd47d86b84f68dbafe92a2](https://user-images.githubusercontent.com/1098808/83952756-da513980-a7ef-11ea-84e7-991899f5fec1.jpg)

**Comment by yse** [comment]
Hello! I think this is MacOS specific bug. We've tested a very little on the MacOS. I'll try to fix it, thanks for feedback.
So - arbitrary values can be found in caption. Example on my linux:
![image](https://user-images.githubusercontent.com/1775230/83953802-2e8a0700-a84c-11ea-80f5-de6f65fb133e.png)

**Comment by andreyryabov** [comment]
No caption fo Arbitrary Value on macOS. 
<img width="1105" alt="Screen Shot 2020-06-06 at 1 31 03 PM" src="https://user-images.githubusercontent.com/1098808/83954016-3caf3780-a7fa-11ea-8eb7-fb311c58ed1b.png">

Caption without value of Event.
<img width="1106" alt="Screen Shot 2020-06-06 at 1 31 23 PM" src="https://user-images.githubusercontent.com/1098808/83954023-4769cc80-a7fa-11ea-9560-453e78dd924d.png">

**Comment by yse** [comment]
So I've made quick fix for MacOS. There is different behaviour of widgets with `Qt::SubWindow` flag on MacOS. I think by the same reason there is bug with absent `Blocks` dialog (from toolbar).     I'll try to fix it also! But I need to gather some information about gui system on mac. Thanks for testing and feedback!

**Comment by andreyryabov** [comment]
Really appreciate the quick fix, helped a lot in my work.
