### ISSUE TITLE
EasySocket::accept() causes deadlock on stopListen()

### ISSUE THREAD

**Issue by rokups** [yse/easy_profiler#19]
calling `stopListen()` deadlocks [here](https://github.com/yse/easy_profiler/blob/develop/easy_profiler_core/profile_manager.cpp#L1190) if listener thread called `EasySocket::accept()` and is waiting on it.

**Comment by yse** [comment]
Thanks for bug report. 
I've created branch `fix/issue19` there fixed the problem under linux. In the near future we will test it on windows and merge after that.
Problem was related to blocking mode of `accept` function. Now it use `select` function for checking connection with timeout.

**Comment by cas4ey** [comment]
Tested on Windows and merged to develop

**Comment by rokups** [comment]
`easy_socket.h` needs `#include <netinet/in.h>` in order to build on android.

**Comment by yse** [comment]
android build [fixed](https://github.com/yse/easy_profiler/commit/a0e1ce459ff35f5ee249edeee8b267fd7497b586)
