### ISSUE TITLE
Make histogram max value depend on visible region

### ISSUE THREAD

**Issue by rokups** [yse/easy_profiler#20]
Consider case where some **very slow** event happens:
![hist1](https://cloud.githubusercontent.com/assets/19151258/23502425/c16c1726-ff2f-11e6-8e9e-7f56831abaa2.png)
Now if we scroll the view to the right and no longer see slow region we get this:
![hist2](https://cloud.githubusercontent.com/assets/19151258/23502447/d2ddc1a8-ff2f-11e6-9a91-0357e822b6bf.png)
Visible data is still hanging at very bottom of the chart making it not really useful. I think histogram range in zoom mode should adapt to visible data instead of entire dataset.

**Comment by cas4ey** [comment]
I have a counter-offer: clip maximum duration manually.

For example press right mouse button (left button and wheel already used) and move mouse up/down to increase/decrease top boundary.

I think this would be better because in adapted mode height of histogram columns will change constantly (as max duration on visible area will change too) while scrolling.

Another argument in favour of such way is that you can also do it in overview mode.

**Comment by facontidavide** [comment]
+1 for this feature ;)
I am not very sure about the usability of right button + move up/down, though

**Comment by rokups** [comment]
I would like it auto as well, but i must admit argument about constantly changing histogram does make sense. Histogram generation can be expensive operation - we often see that "generating" message. If we get bombarded with these delays it would be less usable.

**Comment by cas4ey** [comment]
Hm.. Another suggestion: add an option which should be turned on/off manually (again) but once turned on a median filter would be used to the dataset. This should remove such big values from histogram automatically.

**Comment by cas4ey** [comment]
For those who are waiting for that feature: first manual version of histogram boundary control is ready.
`Shift` + `Mouse Wheel` == adjust _top_ boundary (max duration)
`Ctrl` + `Mouse Wheel` == adjust _bottom_ boundary (min duration)

**Comment by cas4ey** [comment]
Also added possibility to change Expected-frame-time via histogram: use `Ctrl` + `Left mouse button`

**Comment by cas4ey** [comment]
For those who are curious there are several changes to the interface:

Use `Shift` + `Mouse Wheel` to adjust or `Shift` + `LMB` (click) to pick _top_ boundary from histogram;
Use `Ctrl` + `Mouse Wheel` to adjust or `Ctrl` + `LMB` (click) to pick _bottom_ boundary from histogram;
Use `Any modifier` + `RMB` (click) to pick Expected-frame-time from histogram.

Also I have tried to apply median and Gauss filters to a data-set to remove spikes automatically, but this have not provided very good results.

**Comment by cas4ey** [comment]
Done.
Added "Automatically adjust histogram height" option to Settings/View menu.
When turned on, histogram height will be adjusted automatically to the visible region (but this restricts you from adjusting it manually in zoom mode, but you still can adjust boundaries in overview mode).
