### ISSUE TITLE
What is the file format of the profile file, how can it be parsed with software?

### ISSUE THREAD

**Issue by gitartpiano** [yse/easy_profiler#200]
I am planning to use profiling to compare performance of different version of the software. So it is required to compare data in latest and previous profile file. The comparison should be done by software, displaying the performance change. Where do I find info in easy_profiler's documentation about the produced file format? (It would be nice to have this info in or link to it on the ReadMe page.)

**Comment by gitartpiano** [comment]
I am not sure if this is duplicate of issue: https://github.com/yse/easy_profiler/issues/167 . Is the binary format the only supported format?

**Comment by cas4ey** [comment]
Hi @gitartpiano !  

Here is the latest binary file format scheme: [v2.1.0](https://github.com/yse/easy_profiler/wiki/File-format-v2.1.0).  

We got [here](https://github.com/yse/easy_profiler/tree/develop/easy_profiler_converter) a converter to json, but as I remember it is outdated and needs to be modified to be able to work with the latest binary format.

**Comment by gitartpiano** [comment]
Would be nice to be able choose JSON as the output format. But a working converter would be almost as good. Thanks for the tip.
