### ISSUE TITLE
Can this profiler be used for C?

### ISSUE THREAD

**Issue by ASAADASKAR** [yse/easy_profiler#216]
Hello to all,
I would like to ask two questions here, and I look forward to answers. 

I want to use this profiler not only for C++ projects, but also for C projects, is that possible with this profiler?

Is there also a way to use the profiler for low versions, like (C++03)?

**Comment by mariuszmaximus** [comment]
C != C++ 
you need to look for another profiler

**Comment by ASAADASKAR** [comment]
@mariuszmaximus  THX for answer.
 Maybe we can use the profiler for C via a C-compatible interface  or is it not possible?

Do you have an answer to this question, 'Is there also a way to use the profiler for low versions, like (C++03)'?

**Comment by yse** [comment]
@ASAADASKAR 
>Is there also a way to use the profiler for low versions, like (C++03)

Unfortunately, the profiler.h header is built using C++11 features, making it incompatible with C++03 and earlier standards. Backporting it to C++03 would require significant changes, such as replacing modern C++ constructs (e.g., std::chrono, std::thread, or auto) with alternatives available in C++03.
