### ISSUE TITLE
Unused DAFAULT_ADDRESS

### ISSUE THREAD

**Issue by antonovvk** [yse/easy_profiler#26]
Hi!
[There](https://github.com/yse/easy_profiler/blob/develop/easy_profiler_core/include/easy/easy_net.h#L41)'s unused global constant
const char* DAFAULT_ADDRESS = "tcp://127.0.0.1:28077";

Please remove it, because it is:
1. Misspelled
2. Not used
3. Making impossible to build separate profiler lib and gui binary using it, because this constant shows up in different linkage units and than collides.

**Comment by yse** [comment]
Thank you for feedback.
[Fixed](https://github.com/yse/easy_profiler/commit/072fb914672f5569284bde332eb67dfbe05ab382)
