### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [yse/easy_profiler#27]
I would like to point out that an identifier like “[`EASY_PROFILER__OUTPUT_STREAM__H_`](https://github.com/yse/easy_profiler/blob/105d8334e1bc77ca53e240cbc640d519a9d239ab/easy_profiler_core/outstream.h#L31 "Update candidate")” [does eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by yse** [comment]
I think it's some kind of carelessness =) Thanks for advice. Fixed

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/yse/easy_profiler/commit/55000a6325b5e556cf517eaefaaee222c786b289 "Deletion of some underscores").
