### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [yse/easy_profiler#28]
Would you like to [replace any double quotes](https://github.com/yse/easy_profiler/blob/55000a6325b5e556cf517eaefaaee222c786b289/easy_profiler_core/include/easy/profiler_aux.h#L45 "Check inclusion style") by [angle brackets around file names for include statements](https://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by yse** [comment]
`sed` makes a magic! Replaced

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/yse/easy_profiler/commit/15912970db01ded96f07e1cc6a1c9805dc51c46c "Replacement of double quotes by angle brackets").
