### ISSUE TITLE
Missing toolbar icons

### ISSUE THREAD

**Issue by ludekvodicka** [yse/easy_profiler#30]
Hi, in latest version (downloaded today) there are no icons in the app

![profiler_gui_2017-04-11_08-41-35](https://cloud.githubusercontent.com/assets/3900551/24895872/c68f0c40-1e92-11e7-8f75-e607084aa132.png)

**Comment by ludekvodicka** [comment]
Ok, program needs to have Qt5Svgd.dll  in it's own directory. Without that no icons are displayed but also no error message is displayed.

**Comment by valeriovarricchio** [comment]
I am seeing the same in Linux (Ubuntu 16.04). It works if all icons are converted `.png` instead. However, is anyone aware of a better way? @cas4ey

**Comment by rationalcoder** [comment]
@valeriovarricchio There is no way around making sure the svg plugin is in the right spot if the application uses svg files.

**Comment by valeriovarricchio** [comment]
@rationalcoder thanks! You are right, I figured cmake was mixing two clashing versions of Qt on my system. Unfortunately, this was happening 100% quietly.
