### ISSUE TITLE
Empty Hierarchy window

### ISSUE THREAD

**Issue by ludekvodicka** [yse/easy_profiler#33]
Altought I have a lot of EASY_BLOCKs and EASY_FUNCTIONs in my code, I still see empty hierarchy window

![profiler_gui_2017-04-12_10-08-34](https://cloud.githubusercontent.com/assets/3900551/24947709/2056a820-1f68-11e7-857c-54eecf9eb3fd.png)

What should I do to be able to see events also in hierarchy window?

**Comment by rokups** [comment]
While holding right mouse button drag over blocks in thread view. You will see hierarchy view for selected region.

**Comment by ludekvodicka** [comment]
Perfect! Didn't know about this feature. 

Thanks for help and good work with your library.
