### ISSUE TITLE
Empty Hierarchy

### ISSUE THREAD

**Issue by igormironchik** [yse/easy_profiler#35]
After loading *.prof file in the GUI. I can see the Diagram, but Hierarchy is empty.

**Comment by yse** [comment]
You should hold right mouse button and drag over desired blocks in thread view. So, see https://github.com/yse/easy_profiler/issues/33
Unfortunately, our documentation is small yet =(

**Comment by ludekvodicka** [comment]
I believe that small gray text "Use right mouse button ...."  inside the hierarchy window would be a perfect hint.
