### ISSUE TITLE
Design problem with StackBuffer

### ISSUE THREAD

**Issue by rokups** [yse/easy_profiler#37]
I am in the progress of integrating easy_profiler to [AtomicGameEngine](https://github.com/AtomicGameEngine/AtomicGameEngine/pull/1531). In the process we bumped into several nasty issues which i think should be addressed. Profiler does not build on MacOS platform or on windows with MSVC compiler. We worked out [some](https://github.com/AtomicGameEngine/AtomicGameEngine/commit/fc77dac30231926f35e02df1810fe61046872ced) [patches](https://github.com/AtomicGameEngine/AtomicGameEngine/commit/394b7850723d865df6af024d25bba02442c1da2f) and will submit PR once code is in shape.

Now on to a real problem:

MacOS is having a hard time (meaning crash) due to [manual string destructor](https://github.com/yse/easy_profiler/blob/develop/easy_profiler_core/profile_manager.cpp#L615) invocation. This right there is a sign of very bad design and needs to be addressed.

I started digging deeper into the problem and discovered that this destructor call is a result of custom [StackBuffer](https://github.com/yse/easy_profiler/blob/develop/easy_profiler_core/profile_manager.h#L327) class. As i understand this class was created due to performance reasons, but i think it is completely not necessary. Did you try using `std::vector`? We can minimize memory reallocations by reserving space in a vector. I usually reserve double of vector size when capacity is reached. It wastes some memory, but progressively reduces memory reallocations and we can use RAII and not need ugly manual calls to destructors. To avoid copying on insertion we can just `.push_back(std::move(NonscopedBlock(...)))`. This should perform much the same as `StackBuffer` except so much more safer and cleaner.

I started changing `StackBuffer` to `std::vector` and noticed that move constructor of `Block` [modifies](https://github.com/yse/easy_profiler/blob/develop/easy_profiler_core/block.cpp#L80) state of object it is stealing state from. Why? Move constructor is supposed to steal state from the other object and that leaves this object in undetermined state, basically destined for a trashcan. Here something else is happening which seems very wrong. I do not think i can fix this problem without understanding why it was written this way.

**Comment by cas4ey** [comment]
@rokups Please try [this](https://github.com/yse/easy_profiler/commit/593395a4aad81bab55ab7952a70a097f20ac2664) solution for ~string() invokation replacement.

**Comment by cas4ey** [comment]
@rokups Custom stack buffer has been used instead of `std::vector` due to several reasons:
1. Performance: We do not need to invoke `NonscopedBlock` destructor because the only dynamic storage is `std::string` and additionally `profiler::Block` destructor (which is parent class) invokes `profiler::endBlock()` if `m_end < m_begin` - there is no need in all these operations for `NonscopedBlock`.
2. References: We can not use `std::vector` directly because after increasing it's capacity all references to previous elements would be invalidated. If you will inspect `profiler::beginBlock()` you will see that it stores a **reference** to the block.

**Comment by cas4ey** [comment]
@rokups As for modifying `profiler::Block` state on move constructor: this is done to restrict moved `profiler::Block` to invoke `profiler::endBlock()` on it's destructor.

**Comment by cas4ey** [comment]
@rokups Are there any updates for the problem? :)

**Comment by rokups** [comment]
Sorry, i got swamped with other work, but ill get it tested. Didnt forget this ;)

**Comment by rokups** [comment]
@cas4ey sorry for taking forever. String destructor fix solved crash on MacOS. [We are getting there](https://github.com/AtomicGameEngine/AtomicGameEngine/pull/1531#issuecomment-301884770) :)

Since main issue (crash) is solved you may do as you will with this issue, but i still think my earlier mentioned details are quite hairy and there is an opportunity for improvement. Most importantly it works so its good enough for now :)

**Comment by cas4ey** [comment]
@rokups Sorry, I have missed your edits. `GetCurrentThreadId()` in Windows works very fast so there is no need to store thread id in thread-local variable. Thread-local variable (for *nix systems) has been put there on early stage of development when we have got thread id as `std::hash<std::thread::id>(std::this_thread::get_id());`. So maybe now there is no need in thread-local variable, but we should measure `syscall()` duration to be sure.

Also I have replaced `std::string` by `char*` for `NonscopedBlock` so you should not face the problem with string destructor anymore.
