### ISSUE TITLE
Profiler freezes on reconnect

### ISSUE THREAD

**Issue by rokups** [yse/easy_profiler#40]
Reconnecting seems to be broken as profiler application freezes on reconnect. Closing game window does not terminate process as background music can still be heard even if window disappears. Terminating frozen profiler application makes game process exit completely.

Steps to reproduce:

1. Start profiler and profiled application
2. Hit `Connect` button in profiler - data is gathered properly
3. Hit `Stop` button in profiler - data is displayed properly
4. Hit `Disconnect` button in profiler - shouldnt profiler disconnect in previous step?
5. Hit `Connect` button in profiler - profiler is frozen

I should also point out is that we added [this fix](https://github.com/rokups/AtomicGameEngine/blob/fc77dac30231926f35e02df1810fe61046872ced/Source/ThirdParty/easy_profiler/easy_profiler_core/profile_manager.cpp#L1680-L1690) to get profiler into working order. For some reason without this loop profiler freezes on very first attempt to connect to a running application. Killing profiled application shows message that profiler could not connect. This was tested on linux and macos. While i test things with our little bit modified version our mods should not have any impact as they are pretty much all for macos + this loop i just linked.

**Comment by rokups** [comment]
@cas4ey ping :)

**Comment by cas4ey** [comment]
@rokups  sorry for the delay, we have not much time to work on easy_profiler at the moment, but @yse is already working on the problem

**Comment by rokups** [comment]
After i saw some activity yesterday i cant wait for the changes to hit develop so i can test. Thanks 👍

**Comment by yse** [comment]
Well...It was really stupid bug. We forgot close socket on disconnect :-|
