### ISSUE TITLE
Undefined Behavior

### ISSUE THREAD

**Issue by rationalcoder** [yse/easy_profiler#50]
In `profile_manager.h:chunk_allocator::allocate() / emplace_back()` and elsewhere, there are lines like `*(uint16_t*)(data + n) = 0;` and `*(uint16_t*)last->data = 0;`  that violate strict-aliasing rules:

`/easy_profiler/easy_profiler_core/profile_manager.h:175:36: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
             *(uint16_t*)last->data = 0;`

I have confirmed that easy_profiler does not work correctly when cross compiled (with gcc-4.9.4) for a single core ARMv5 (32 bit) Linux, with pthreads enabled. It works, however, on Linux x86_64 with the same compiler version on the same machine used for cross-compiling. This could be direct result of the UB, as I have made similar mistakes that caused code to work on x86 but not the ARM platform I am using. 

Even if my problems aren't caused by the UB, it still needs to be fixed anywhere it is found. I would suggest the use of `std::memcpy` / `std::memset` for such things.

**EDIT** the line `*(uint16_t*)(data + n) = 0` doesn't violate strict-aliasing, only the second one.

**Comment by cas4ey** [comment]
Hi, @rationalcoder !
Thank you for reporting the issue!
Taking it into the work :-)

**Comment by rationalcoder** [comment]
@cas4ey  Do you know what platforms this is known to work on other than x86 and x86_64?

**Comment by cas4ey** [comment]
@rationalcoder, I'm not really sure. Initially it has been developed for desktop x86 and x86_64 (Windows, Linux, MacOS), but I know that guys from [AtomicGameEngine](https://github.com/AtomicGameEngine/AtomicGameEngine) are also using it on Android on phones and tablets so it should work on some ARM platforms I think.
@rokups , @JoshEngebretson , can you please clarify for which platforms have you used easy_profiler?

**Comment by rokups** [comment]
Can confirm easy_profiler was working on arm 32bit compiled with clang from ndk. Profiler GUI was compiled on linux x64 (gcc).

**Comment by rationalcoder** [comment]
@rokups Well, I am compiling for an ARM926EJ-S, which is pretty old and single core, so I guess complications can be expected. If and when I find the issue, I will either let it be known here or make a pull request for it.

**Comment by cas4ey** [comment]
I think the issue could be related to Little-/Big-endian differences on profiled ARM platform and on a PC running GUI/reader.

Also sizes of some core types may differ, but we tried to use std types from `stdint.h` everywhere, but there is a possibility that we could miss something.

The only place I remember is `BaseBlockDescriptor::m_line` which has `int` type. You can find it [here](https://github.com/yse/easy_profiler/blob/develop/easy_profiler_core/include/easy/profiler.h#L477).

You can try to replace it with `int32_t` explicitly - maybe this could help.

**Comment by rationalcoder** [comment]
@cas4ey That is what I was thinking at first. Then, I ran my sample application and the reader on the ARM platform, and it still didn't work. Do you guys have guidelines on how you like contributions to be done?

**Comment by cas4ey** [comment]
I'll duplicate the answer (which I sent by email) for the others.

We do not have any specific guidelines yet. I think it would be enough to create pull request with proper descriptio (what was fixed or changed) and the issue number inside it's commits (commit message example: #50 fixed endianness problem while writing to file). It would be good if a code style would match other code in the library.

@rationalcoder, I hope I get your question right.

@yse please correct me if I'm wrong.
