### ISSUE TITLE
EASY_ENABLE_ALIGNMENT Broken for GCC (Non-MinGW)

### ISSUE THREAD

**Issue by rationalcoder** [yse/easy_profiler#51]
This code in profile_manager.h:126 is broken for plain GCC:

`#if EASY_ENABLE_ALIGNMENT == 0`
`# define EASY_ALIGNED(TYPE, VAR, A) TYPE VAR`
`# define EASY_MALLOC(MEMSIZE, A) malloc(MEMSIZE)`
`# define EASY_FREE(MEMPTR) free(MEMPTR)`
`#else`
`# if defined(_MSC_VER)`
`#   define EASY_ALIGNED(TYPE, VAR, A) __declspec(align(A)) TYPE VAR`
`#   define EASY_MALLOC(MEMSIZE, A) _aligned_malloc(MEMSIZE, A)`
`#   define EASY_FREE(MEMPTR) _aligned_free(MEMPTR)`
**`# elif defined(__GNUC__)`
`#   define EASY_ALIGNED(TYPE, VAR, A) TYPE VAR __attribute__(aligned(A))`
`# else`**
`#   define EASY_ALIGNED(TYPE, VAR, A) TYPE VAR`
`# endif`
`#endif`

The code in the `#elif defined(_GNUC_)`: 
    `#  define EASY_ALIGNED(TYPE, VAR, A) TYPE VAR __attribute__(aligned(A))` 
should be:
    `#  define EASY_ALIGNED(TYPE, VAR, A) TYPE VAR __attribute__((aligned(A)))` (missing a set of parentheses)

Once that is fixed, both EASY_MALLOC and EASY_FREE need to be defined to some reasonable value which is up to you guys, since there are a few candidates.

**Comment by cas4ey** [comment]
@rationalcoder Thank you for testing a build :-)
@yse can you please resolve the issue?
