### ISSUE TITLE
why hierarchy is empty？

### ISSUE THREAD

**Issue by chena1982** [yse/easy_profiler#52]
the thread timeline is correct, but the hierarchy is empty.
i use easy_function and easy_block.
need set something?
Thanks.

**Comment by rokups** [comment]
Shift-right-click-drag over timeline IIRC.

**Comment by chena1982** [comment]
It works, thanks.

**Comment by cas4ey** [comment]
There is a hint in empty hierarchy window.
Isn't it visible? (I'm serious: maybe we should create new issue)

**Comment by rokups** [comment]
We probably need some kind of help window with common shortcuts.

**Comment by chena1982** [comment]
it's visible, sorry, it's my fault.
maybe should change the hint's color.
