### ISSUE TITLE
QFont intialized before QApplication causes segfault with static Qt

### ISSUE THREAD

**Issue by oliverdaniell** [yse/easy_profiler#54]
Initialization of fonts before QApplication is not valid and causes a segfault when linking statically against Qt. This is caused by the initialization of non-local variables before main. eg.

`const auto BG_FONT = ::profiler_gui::EFont("Helvetica", 10, QFont::Bold);`

This can be fixed by replacing the above with

`auto const & BG_FONT()
{
    static const auto BG_FONT = ::profiler_gui::EFont("Helvetica", 10, QFont::Bold);
    return BG_FONT;
}
`

**Comment by oliverdaniell** [comment]
If you agree with the fix I can create a merge request

**Comment by yse** [comment]
@oliverdaniell thanks for report. 
Of course, you can create request - it will be good!

**Comment by cas4ey** [comment]
local static `QFont` may cause problem on VS2013 because it has no c++11 magic statics support.
Please, move it into `EASY_GLOBALS`

**Comment by oliverdaniell** [comment]
The issue came up on gcc 5.4 so I don't think it's related to differences in the handling of static between c++98 and c++11 (I assume by c++11 magic statics you mean the thread safe initialization?). I'm not sure why the code works when linking dynamically against Qt. From the [doc](http://doc.qt.io/qt-5/qfont.html)

> Note that a QGuiApplication instance must exist before a QFont can be used

 Anyway EASY_GLOBALS looks like the logical place to put it so I will get that done tomorrow.

**Comment by cas4ey** [comment]
> The issue came up on gcc 5.4 so I don't think it's related to differences in the handling of static between c++98 and c++11 (I assume by c++11 magic statics you mean the thread safe initialization?).

Yes, I mean thread safe initialization. I just wanted to say that hiding `static QFont` inside a function would add additional problems for VS2013 users.

> Anyway EASY_GLOBALS looks like the logical place to put it so I will get that done tomorrow.

Nice 👍
