### ISSUE TITLE
Procedure point can't be located in DLL

### ISSUE THREAD

**Issue by Epaenetus** [yse/easy_profiler#59]
I keep getting this pop-up error on launch whenever I try to run profiler_gui.exe in anything other than debug. (In debug, the profiler open and seems to work just fine)

My current setup is using Visual Studio 2015, x64 and Qt5.9.1. Do you know if this is local issue on my computer or an issue with the project?

---------------------------
profiler_gui.exe - Entry Point Not Found
---------------------------
The procedure entry point ??4QColor@@QEAAAEAV0@$$QEAV0@@Z could not be located in the dynamic link library E:\easy_profiler\visual_studio\bin\Release\profiler_gui.exe. 
---------------------------

**Comment by rationalcoder** [comment]
That almost certainly a problem with your setup. For some reason, the loader is trying to load profiler_gui.exe as a DLL, which it clearly isn't. Even weirder, it's looking for something that isn't a symbol and looks like it is from the Qt library... Please open your build configuration in Visual Studio and compare your debug C/C++ options with the other build types. I assume something will be obviously wrong.

**Comment by cas4ey** [comment]
@Epaenetus, I have built easy_profiler with VS2015 and Qt 5.8 (but it was a couple month ago and it isn't Qt 5.9), both Debug and Release builds were working as expected.
It seems that you have some troubles with Qt paths...  Debug Qt binaries have been found successfully, but release ones - not.

**Comment by rationalcoder** [comment]
@cas4ey I don't know why he deleted his comment, it seemed like the problem was figured out, and it wasn't with easy_profiler.

**Comment by Epaenetus** [comment]
Thanks for the replies! I've been busy with work and haven't gotten a chance to look in detail into this since last weekend. I'll look into my paths and see if that is the issue. I don't think its an issue with build configurations as that should all be taken care of automatically with CMake. However, to be safe I did briefly look through those settings and nothing stood out as obviously wrong.

I'll let you know if I find anything!

**Comment by Epaenetus** [comment]
@rationalcoder I didn't post a comment earlier and delete it so I think you might be mistaken with a different thread.

**Comment by rationalcoder** [comment]
@Epaenetus Now that you mention it, I think it was someone else, still on this thread though. My bad. His problem was with different qt versions I think. Make sure that your include and library paths are correct in all configurations, the right libraries are listed for linker input, and the correct Qt DLL versions are being loaded. In debug builds your linker inputs should be <qt library name>d.lib . and the <qt library name>d.dll should be copied to your executable directory. If you can't figure it out, feel free to email me pictures of the relevant C/C++ settings pages.

**Comment by Epaenetus** [comment]
So it was apparently an issue with my paths as cas4ey mentioned. I had to use the where command to find out that I had a conflicting dll in my path from PyQT. Thanks for the help @cas4ey  & @rationalcoder !
