### ISSUE TITLE
Starting and ending a block from two functions

### ISSUE THREAD

**Issue by kkirby** [yse/easy_profiler#60]
Hi,

I'm wanting to start and end a block manually in two functions. I want to use the GCC API for start and end functions so I don't have to add the easy_profiler macros to every function call.

Something like:

```c++
void __cyg_profile_func_enter(void* this_fn, void* call_site){
	const char* symbol = "";
	Dl_info info;
	if(dladdr(this_fn, &info) && info.dli_sname){
		symbol = info.dli_sname;
	}

	int status = 0;

	char* demangled = __cxxabiv1::__cxa_demangle(symbol, 0, 0, &status);
	EASY_PROFILE_BLOCK_START(demangled != NULL && status == 0 ? demangled : symbol);
	infunc = false;
}

void __cyg_profile_func_exit(void* this_fn, void* call_site){
	EASY_PROFILE_BLOCK_END();
}
```

Is this possible?

**Comment by yse** [comment]
Hello. Thanks for feedback

You should use `EASY_NONSCOPED_BLOCK(name)` (at the start) and `EASY_END_BLOCK` (at the finish) in this case. For more information see: https://github.com/yse/easy_profiler/issues/29 and documentation in header: https://github.com/yse/easy_profiler/blob/develop/easy_profiler_core/include/easy/profiler.h#L118

**Comment by kkirby** [comment]
That's what I thought, but this comment confused me: https://github.com/yse/easy_profiler/blob/2a235d47d919a46d5e8bc7404fa9d101d6909f97/easy_profiler_core/include/easy/profiler.h#L145

Thanks!
