### ISSUE TITLE
Forced Optimization on Unix

### ISSUE THREAD

**Issue by rationalcoder** [yse/easy_profiler#61]
Now, I could be doing something stupid, but I'm pretty sure easy_profiler_core doesn't respect the build type option because of this cmake code in `easy_profiler_core/CMakeLists.txt`. **Note the -O3**
```
if (UNIX)
    target_compile_options(easy_profiler PRIVATE -Wall -Wno-long-long -Wno-reorder -Wno-braced-scalar-init -pedantic -O3)
    target_link_libraries(easy_profiler pthread)
elseif (WIN32)
    target_compile_definitions(easy_profiler PRIVATE -D_WIN32_WINNT=0x0600 -D_CRT_SECURE_NO_WARNINGS -D_WINSOCK_DEPRECATED_NO_WARNINGS)
    target_link_libraries(easy_profiler ws2_32 psapi)
endif ()
```

I have been trying to debug an issue on my ARM platform for quite sometime now, and this really through me off. I had ruled out UB because it was still broken in the debug build...

**Comment by yse** [comment]
It's a good point to separate the build types by `CMAKE_BUILD_TYPE`. In Debug build some flags (such as `-ggdb`) are useful. I'll make it. Thanks for feedback =)

**Comment by rationalcoder** [comment]
@yse Why do you need to add the optimization flags if they are added already? Do the optimization flags not get set correctly on some Unix platforms?

**Comment by yse** [comment]
@rationalcoder Yes, you are right! I have check the default optimization flags. At the Release CMake set `-O3` but at the Debug set only `-g`. I'll remove useless code in few minutes.
