### ISSUE TITLE
Compile Problems

### ISSUE THREAD

**Issue by keksoe** [yse/easy_profiler#64]
Hello,

so I am trying to test-profile an application of mine on a Windows 7 x64 machine. 

I use MinGW compiler version 4.9.1 .

So here is the code:
```
#include <iostream>
#include <easy/profiler.h>

...

int main(){
	EASY_PROFILER_ENABLE;
	printf("%d",fibonacci(30));
	profiler::dumpBlocksToFile("test_profile.prof");
}
```
Since I am using eclipse together with MinGW , i get to chose some arguments for the compilation...

When I compile as follows:
`g++ -std=c++0x -DBUILD_WITH_EASY_PROFILER "-IC:\\Users\\EMAKMEL\\Desktop\\gradle-test\\54profiling\\easy_profiler-v1.2.0-msvc12-win64\\bin" "-IC:\\Users\\EMAKMEL\\Desktop\\gradle-test\\54profiling\\easy_profiler-v1.2.0-msvc12-win64\\include" -O0 -g3 -Wall -c -fmessage-length=0 -o file.o "..\\file.cpp" ` 

Everything is okay so far...
However when eclipse tries to execute:

`g++ -DBUILD_WITH_EASY_PROFILER "-LC:\\Users\\EMAKMEL\\Desktop\\gradle-test\\54profiling\\easy_profiler-v1.2.0-msvc12-win64\\bin" "-LC:\\Users\\EMAKMEL\\Desktop\\gradle-test\\54profiling\\easy_profiler-v1.2.0-msvc12-win64\\include" -o profiledproject.exe file.o `

I get : `undefined reference to '__imp_setEnabled' ` and `undefined reference to '__imp_dumpBlocksToFile'`

If I take out the `-DBUILD_WITH_EASY_PROFILER` then it all compiles nicely and executes.... 

Thank you in advance for your help,
Regards,
Maksim Melnik

**Comment by rokups** [comment]
That is linker error. Did you link to easy_profiler lib?

**Comment by keksoe** [comment]
Oh, yeah, added `-leasy_profiler` to the end of the linking line and it solved the problem... Thanks

**Comment by keksoe** [comment]
Now however, if i add `EASY_FUNCTION(profiler::colors::Magenta);`  , i get the `undefined reference to '__imp__ZN8profiler5BlockC1EPKNS_19BaseBlockDescriptorEPKcb'`

**Comment by keksoe** [comment]
Here is my main function now:

```
int main(){
	EASY_PROFILER_ENABLE;
	EASY_FUNCTION(profiler::colors::Magenta);
	printf("%d",fibonacci(30));
	profiler::dumpBlocksToFile("test_profile.prof");
}
```

**Comment by rationalcoder** [comment]
@keksoe If you really are linking correctly, it may an ABI incompatibility. I would try building it from source with CMake. If you are good enough with Microsoft tools(or MinGW tools), you could dump the symbols in the easy_profiler DLL and grep for `BaseBlockDescriptor` and see what is there, if anything.

**Comment by keksoe** [comment]
@rationalcoder 

> I would try building it from source with CMake.

By "it" do you mean my project or the easy_profiler?

**Comment by keksoe** [comment]
@rationalcoder 
So i decided to try compiling my application with cmake.
At this point I am using the Cmakelist from the readme
```
project(app_for_profiling)

set(SOURCES
    file.cpp
)

#CMAKE_PREFIX_PATH should be set to <easy_profiler-release_dir>/lib/cmake/easy_profiler
find_package(easy_profiler REQUIRED)

add_executable(app_for_profiling ${SOURCES})

target_link_libraries(app_for_profiling easy_profiler)
```

When I run this , i get an error that cmake_minimum_required command is not present.
When I add this command `` though , i get this message ` Could not find a configuration file for package "easy_profiler" that is compatible with requested version "".`
Am I doing something wrong?
Sorry for noob questions... First time I am using cmake...

**Comment by keksoe** [comment]
@rationalcoder 
if i try to add version as follows
```
find_package(easy_profiler 1.2.0 REQUIRED)
```
I am still getting the same error:
```
 Could not find a configuration file for package "easy_profiler" that is
 compatible with requested version "1.2.0".

    C:/Users/EMAKMEL/Desktop/gradle-test/54profiling/easy_profiler-v1.2.0-msvc12-win64/lib/cmake/easy_profiler/easy_profilerConfig.cmake, version: 1.2.0 (64bit)
```

**Comment by cas4ey** [comment]
Try `cmake -DCMAKE_PREFIX_PATH="C:/Users/EMAKMEL/Desktop/gradle-test/54profiling/easy_profiler-v1.2.0-msvc12-win64/lib/cmake/easy_profiler"` instead of just `cmake`

**Comment by rationalcoder** [comment]
@keksoe I meant building easy_profiler with cmake. When a library comes with cmake build scripts, it's normally easiest to open them up with Qt Creator, CMake GUI, or use cmake to generate a VS project file and build it from there. Then, once you have the library built, you can create an easy_profiler directory in some middleware directory, copy over DLLs, libs, and include directory over to it, and specify those in the build system that you prefer to use for development.

**Comment by cas4ey** [comment]
@keksoe Are there any news on the issue?

**Comment by rationalcoder** [comment]
I am almost certain that this is an ABI incompatibility. This is the issue with not having a C API on the DLL boundary. You just need to build easy profiler itself, from source, with cmake, and making sure that CXX is set to your MinGW g++ or whatever compiler you want to use to compile your application.

**Comment by cas4ey** [comment]
Closing the issue since there are no any updates for a long time.
