### ISSUE TITLE
GUI Crashes and Connection Issues.

### ISSUE THREAD

**Issue by rationalcoder** [yse/easy_profiler#66]
If you hit cancel while the client is sending blocks, the GUI crashes. Also, if there is a disconnection due to the client crashing or whatever, all future connection attempts fail immediately; you have to restart the GUI.

**Comment by cas4ey** [comment]
O_O

**Comment by cas4ey** [comment]
@yse I remember that you wanted to look at this bug, right?

**Comment by Silveryard** [comment]
I have these two issues too. I use this tool a lot but currently I only can profile with .prof files to avoid crashes and restarts

**Comment by yse** [comment]
so, first of all, I've fixed gui crashing. Client disconnection problem fixing coming soon =)

**Comment by cas4ey** [comment]
@rationalcoder , @Silveryard , guys can you, please, test the last changes? It must be working now, whithout restarting gui.

**Comment by cas4ey** [comment]
v1.3.0 released. Closing
