### ISSUE TITLE
Time Legend is wrong on GUI (off by one) once the scale is at or above 1s

### ISSUE THREAD

**Issue by rationalcoder** [yse/easy_profiler#68]
![issue22-1](https://user-images.githubusercontent.com/13477550/30498111-102147ac-9a1b-11e7-9ede-3726cc574269.PNG)
![issue22-2](https://user-images.githubusercontent.com/13477550/30498109-101d3aea-9a1b-11e7-86cd-33f4c1e576b5.PNG)
![issue22-3](https://user-images.githubusercontent.com/13477550/30498108-101baee6-9a1b-11e7-9421-ca18c53306c7.PNG)
![issue22-4](https://user-images.githubusercontent.com/13477550/30498110-101f39b2-9a1b-11e7-8a7c-e7dc746e1935.PNG)

**Comment by cas4ey** [comment]
@rationalcoder Can you please test this [commit](https://github.com/yse/easy_profiler/commit/a3ba063e70669d5361228551f9af31f381542104)?

**Comment by rationalcoder** [comment]
@cas4ey I don't know if there is a formal github review thing I can do, but I can confirm that this works for me.

**Comment by rationalcoder** [comment]
@cas4ey Not sure if closing this myself is the right thing to do, so I am going to let you do it when you are ready.

**Comment by cas4ey** [comment]
@rationalcoder You are the author and reviewer so why not :)

**Comment by rationalcoder** [comment]
@cas4ey Just making sure. I will close it myself from now on.
