### ISSUE TITLE
macOS

### ISSUE THREAD

**Issue by hexabyte23** [yse/easy_profiler#70]
Hi,
When do you plan to fully support macOS ?

**Comment by rokups** [comment]
What is missing? We had profiler was working on MacOS for quite some time now.

**Comment by cas4ey** [comment]
I think I could broke MacOS build after moving sources to several different files :fearful: 
But I'm not sure, need to hear the answer :)

**Comment by hexabyte23** [comment]
try to compile last 1.3.0 version with QtCreator4.41/Qt 5.9.1, get this:

CMake Warning at profiler_gui/CMakeLists.txt:7 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.

**Comment by rokups** [comment]
Warning just told you what to do.

**Comment by hexabyte23** [comment]
ok, sorry guys. My bad. I succeed to compile core, and fails to compile gui part.

Seems Qt env not set properly, as I get this:

 Could not find a package configuration file provided by "Qt5Widgets" with
  any of the following names:

    Qt5WidgetsConfig.cmake
    qt5widgets-config.cmake

  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set
  "Qt5Widgets_DIR" to a directory containing one of the above files.  If
  "Qt5Widgets" provides a separate development package or SDK, be sure it has
  been installed.


INFO

	Qt5 not found! Generating EasyProfiler projects without GUI.

**Comment by rokups** [comment]
You have to add path pointing to Qt installation to `CMAKE_PREFIX_PATH` variable. Do as warning says.

`cmake -DCMAKE_PREFIX_PATH=/path/to/your/Qt5`

You installed Qt with homebrew right?

**Comment by cas4ey** [comment]
Also you can create env variable `${Qt5Widgets_DIR}="<path to Qt5>/lib/cmake/Qt5Widgets"`

**Comment by hexabyte23** [comment]
succeed to compile both on macOS, thanks a lot...

**Comment by buddhisthead** [comment]
For my own notes...
Mac M1:
```
brew install qt
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/opt/homebrew/Cellar/qt@5/5.15.9/lib/cmake/Qt5Widgets/ ..
```
