### ISSUE TITLE
Do not force -std=gnu++11 flag on target projects

### ISSUE THREAD

**Issue by cdsousa** [yse/easy_profiler#71]
Hi, thanks for this great work!

I'm trying to use easy_profiler on a C++14 project where I do in CMakeLists.txt something like
```cmake
add_compile_options(-std=c++14)
```
However, the dependency on easy_profiler, which is defined with
```cmake
target_link_libraries(my_app easy_profiler)
```
is making the easy_profile compilation option `-std=gnu++11` take precedence over the C++14 flag, therefore the compiler gives errors due to my code having C++14 constructions...

I already tried doing 
```cmake
target_compile_options(my_app PRIVATE -std=c++14)
```
after the but easy_profiler line, but I had no success.

**Comment by yse** [comment]
Hi. Thanks for feedback.
I've reproduced the bug! As temporary solution I can advice manually replace exported flag (line `52`) in `easy_profilerTargets.cmake` file (located in `lib/cmake/easy_profiler` from release package) or run script: `sed -i 's/11/14/g' easy_profilerTargets.cmake`

In next release we will fix it!

**Comment by cdsousa** [comment]
I've just done such workaround, and it worked. Many thanks!

**Comment by yse** [comment]
Also you should specify standard by the following method:
```cmake
set(CMAKE_CXX_STANDARD 14)
```
It will set `-std=c++14` option to the compiler at the end and the flag will precedence over previous `-std` flags.
