### ISSUE TITLE
Failed to build easy_profiler as static library

### ISSUE THREAD

**Issue by cxyzs7** [yse/easy_profiler#76]
In the library's CMake file (https://github.com/yse/easy_profiler/blob/develop/easy_profiler_core/CMakeLists.txt), `BUILD_SHARED_LIBS` is defined but not used; on the other hand, `EASY_OPTION_LIB_STATIC` is used but not defined anywhere:

```
set(BUILD_SHARED_LIBS                  ON     CACHE BOOL   "Build easy_profiler as shared library.")
...
if (EASY_OPTION_LIB_STATIC)
    target_compile_definitions(easy_profiler PUBLIC -DEASY_PROFILER_STATIC=1)
endif ()
```
When building with Visual Studio 2015 (Version 14.0.25431.01 Update 3), it generated several `unsolved external symbol` errors:
```
main.obj : error LNK2019: unresolved external symbol __imp_dumpBlocksToFile referenced in function main
5>main.obj : error LNK2019: unresolved external symbol __imp_startListen referenced in function main
5>main.obj : error LNK2019: unresolved external symbol __imp_main_thread_frameTimeLocalMax referenced in function "public: void __cdecl <lambda_d4b84504febb1e9470831de2a62f1e36>::operator()(void)const " (??R<lambda_d4b84504febb1e9470831de2a62f1e36>@@QEBAXXZ)
3>main.obj : error LNK2019: unresolved external symbol __imp_setEnabled referenced in function main
3>main.obj : error LNK2019: unresolved external symbol __imp_dumpBlocksToFile referenced in function main
...
```
Changing the `EASY_OPTION_LIB_STATIC` check to use `BUILD_SHARED_LIBS`  seemed to solve the problem, but I am not sure if it's intended use of the variable:

```
if (NOT BUILD_SHARED_LIBS)
    target_compile_definitions(easy_profiler PUBLIC -DEASY_PROFILER_STATIC=1)
endif ()
```

**Comment by rationalcoder** [comment]
Your change does make sense as far as I can tell, but, since `BUILD_SHARED_LIBS` is built into cmake, all you should have to do to build a static library is turn that off. I have never had to set `EASY_OPTION_LIB_STATIC`. That being said, this does look like something that needs to be addressed. Maybe it is some code rot?

Also, those errors indicate that an import library, as opposed to a static library, was linked against, causing the loader to try to resolve those symbols at load-time with easy_profiler.dll, which wasn't built/available.

**Comment by cxyzs7** [comment]
@rationalcoder 
I think `EASY_OPTION_LIB_STATIC` is used in easy/easy_compiler_support.h:

```
#if defined(_WIN32) && !defined(EASY_PROFILER_STATIC)
// Visual Studio and MinGW
# ifdef _BUILD_PROFILER
#  define PROFILER_API __declspec(dllexport)
# else
#  define PROFILER_API __declspec(dllimport)
# endif
#endif
```

If `EASY_PROFILER_STATIC` is not defined, all the APIs will be marked as `__declspec(dllexport)` during build time even it's built as a static library, I think this makes Visual Studio unhappy when building the executable.

**Comment by rationalcoder** [comment]
Then yes, that probably does need to be changed; however, I am not sure how this ever worked then? Maybe all of the tests have been with shared libraries? Maybe static libraries have only been tested on Linux (where this doesn't matter)? I would say that you should:

1. Wait for one of the two main developers to look at this.
2. Make a pull request with the change to that if statement, and
3. Don't do anything besides turn BUILD_SHARED_LIBS off when you want to build a static library.

**Comment by yse** [comment]
Hello. Thanks for feedback! We forget about this flag while refactoring =) See commit 36bade193924c840c5c603667c169c7832256afe
