### ISSUE TITLE
No full method names on RPI

### ISSUE THREAD

**Issue by heretique** [yse/easy_profiler#81]
Hi,
I'm using your great profiler to profile an application running on Raspberry Pi, everything works great except the method names are not fully qualified. I get only the method name without the class name as it is shown in your screenshots. Is there an option when configuring the profiler that I may have missed?
I've attached a screenshot showing my issue.

![easy_profiler_capture](https://user-images.githubusercontent.com/139596/32980235-65ba4c4a-cc6b-11e7-8c52-5df43c0c7d28.png)

**Comment by cas4ey** [comment]
Hi @heretique 
Thanks for good words.
This issue doesn't refer to Raspberry Pi only, but for Unix systems.
Windows `__FUNCTION__` contains class name and function name.
Unix version of this macro/var contains only function name.
You can replace it with `__PRETTY_FUNCTION__`, but it contains also types of function parameters and type of returned result.
Without modification of core API you can replace all `EASY_FUNCTION()` with `EASY_BLOCK(__PRETTY_FUNCTION__)` in your code.
I think we would add a possibility to chose verbosity of function names into release 2.0

**Comment by cas4ey** [comment]
Updated previous comment

**Comment by heretique** [comment]
Thanks for the info, keep up the good work ;)

**Comment by cas4ey** [comment]
Implemented and would be released in release v2.0
