### ISSUE TITLE
Using this library with mingw_5.3.0

### ISSUE THREAD

**Issue by GentleHedgehog** [yse/easy_profiler#85]
I try to use your application with my own using mingw 5.3.0 32bit (Qt5.7.0). But I get an error like this - "undefined reference to `_imp__startListen'". In .pro file I wrote:

INCLUDEPATH += "mypath\easy_profiler-v1.3.0-msvc14-win64\include"
LIBS += "mypath\easy_profiler-v1.3.0-msvc14-win64\bin\easy_profiler.lib"
DEFINES += BUILD_WITH_EASY_PROFILER

Then I realized that libraries from MSVC are not compiled by the MinGW compiler. Could you try to support library for MingGW or any other workaround?

**Comment by rationalcoder** [comment]
There are 2 problems here:
1. Your `LIBS` line is incorrect. It should be of the form: "LIBS += -L<library path> -l<library name>".
2. You are trying to use the 64-bit msvc library from mingw32 (32-bit), as you have noticed. easy_profiler _does_ have support for mingw32 in that it is built with cmake. To build your mingw32 library, open the highest level CMakeLists.txt in Qt Creator, and make sure you have the mingw 5.2.0 32-bit build kit selected. Click build and there you go. If that is annoying or you can't do it for some reason. You can manually build it with CMake GUI, specifying the mingw toolchain that comes in the `Tools` directory of your `Qt` installation, likely at `C:\Qt\Tools\mingw32-5.3.0\bin`

**Comment by GentleHedgehog** [comment]
this is the perfect explanation, thanks!

**Comment by rationalcoder** [comment]
No problem. If you no longer have a problem, consider closing this issue.
