### ISSUE TITLE
Snapshot Support

### ISSUE THREAD

**Issue by rationalcoder** [yse/easy_profiler#91]
At my work, I am trying to enforce the practice of providing before-and-after profiling results of patches that claim to have made something faster, along with providing profiling results when claiming that something is slow in the first place. This is currently annoying, as a capture might be 10+ seconds long, with only a small portion of it containing an example of the issue.

I would like the ability to select a region and be able to export only it into a smaller .prof file. In addition, I would like to be able to add notes at certain time-stamps. That would be useful if, for example, there are two or more frame spikes in question that are dependent on each other in some way. 

Snapshots should contain the relevant FPS and user-defined metrics that are introduced in the future, so that notes can reference that data. In addition, snapshots should contain enough information for the GUI to reproduce at least the zoom level / vertical scroll % (to take you right to a problematic thread).

I imagine this being optional data defined to be stored after the usual contents of a .prof. That way, any additional overhead is only on the GUI side, where it doesn't matter.

**Comment by cas4ey** [comment]
Thanks for suggestion! :)
Sounds easy to implement in terms of back-end, but a bit more harder for convenient front-end (and to integrate it in existing ui)...
Currently I'm the only front-end developer and I still have a lot of work to do on arbitrary values (user-defined metrics). But I agree that this feature is a must-have. I will create a milestone for it.

**Comment by rationalcoder** [comment]
I will see if I can start familiarizing myself enough to start contributing there. I feel like I should be able get into it given my Qt background.

**Comment by cas4ey** [comment]
Hey @rationalcoder
The snapshot feature is implemented :-)

I will create separate issue for [user notes support]
