### ISSUE TITLE
Bugs and Known Issues Wiki Addition

### ISSUE THREAD

**Issue by rationalcoder** [yse/easy_profiler#92]
I am getting annoyed with trying to fork/make PRs, but I would like to add a new entry to the known issues part of the wiki:

### GCC6 and earlier on single-core ARM (ARMv5, for sure.) 
Prior to GCC7, there is a bug with std::future on (at least) ARMv5 which manifests itself as a linker error. Specifically, you will get an undefined reference to std::future's vtable. To get easy profiler to build, you will need to manually apply [this](https://gcc.gnu.org/bugzilla/attachment.cgi?id=39971&action=edit) patch (plus a similar change to future.cc which isn't mentioned in the patch) to GCC's source code before building it. If you aren't building your cross-compiler from source, it would seem that you are out of luck, and you will just have to get GCC7+.

**Comment by yse** [comment]
Hi. Thanks a lot for wiki! It was [added](https://github.com/yse/easy_profiler/wiki/Known-bugs-and-issues#building)
