### ISSUE TITLE
Any plans for Mac OSX

### ISSUE THREAD

**Issue by heretique** [yse/easy_profiler#98]
Hi, are there any plans to support Mac OSX for the upcoming 2.0 release?

**Comment by rokups** [comment]
I believe there is nothing that really prevents profiler working on MacOS. We had 1.5 running on MacOS just fine. Might have patched few things though, but nothing major.

**Comment by heretique** [comment]
I see, i was asking because I didn't see any section related to Mac OSX in the readme file and I remember that I had some issue with 1.3 on Mac OSX in the past. I will give 1.5 a try. Thanks

**Comment by rokups** [comment]
Looks like 1.5 was never released. Anyway i always keep updating to latest code on `develop` branch. You may try latest release which is 2.0 beta. I havent really had any bad experience while using non-release code :)

**Comment by lahwran** [comment]
Hey, I also came to the issues section looking for information on OSX. Could you stick some information about how to get it set up on mac in the docs?

**Comment by yse** [comment]
@lahwran try something like (as we do on [travis](https://github.com/yse/easy_profiler/blob/develop/.travis.yml#L53) osx build):
```bash
#prepare build environment
brew install gcc5
brew install qt55
brew link --force qt55
export QT_NAME="qt@5.5"
export HOMEBREW_QT5_VERSION=$(brew list --versions $QT_NAME | rev | cut -d' ' -f1 | rev)
ln -s /usr/local/Cellar/$QT_NAME/$HOMEBREW_QT5_VERSION/mkspecs /usr/local/mkspecs
ln -s /usr/local/Cellar/$QT_NAME/$HOMEBREW_QT5_VERSION/plugins /usr/local/plugins

#build 
cmake -DCMAKE_CXX_COMPILER=g++-5 -DCMAKE_C_COMPILER=gcc-5 $PATH_TO_EASY_PROFILER_SOURCE
make
```

__Note__: As fas as I know there are some problems with building qt apps with xcode8 _clang_ compiler but this is not so actual information. We haven't mac for testing =(

**Comment by avlbanuba** [comment]
Hi! We are using easy_profiler for application on MacOSX. There is now problems with that, both profiling lib and gui works fine.
