### ISSUE TITLE
CPU time 

### ISSUE THREAD

**Issue by Mennat-Ullah** [yse/easy_profiler#99]
Hello,

can easy_profiler  calculate or use  CPU time ?
if yes , how can i find or use it ?

Thanks,

**Comment by cas4ey** [comment]
Hi @Mennat-Ullah 

It stores raw ticks count received from system timer. These ticks are converted to nanoseconds by the UI.

Possible timers are:
- rdtsc (this is default for Linux, Mac and other *nix systems);
- QueryPerformanceCounter (Windows only and this is default for Windows);
- `std::chrono::high_resolution_clock`;
- `std::chrono::steady_clock`.

Only rdtsc returns truly CPU ticks as I know (and maybe `std::chrono`, but it depends on system).

If you are interested in using EasyProfiler just for getting ticks then you can use API function `profiler::currentTime()`. These ticks could be converted to nanoseconds or microseconds with `profiler::toNanoseconds()` or `profiler::toMicroseconds()`.
But using the profiler **just** for this purpose is overkill. I suggest you to use one of the timers mentioned above in such case.
